name: tests

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  release_sphinx:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:

      # check out sources that will be used for autodocs, plus readme
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync
      # didn't need to change anything here, but had to add sphinx.ext.githubpages
      # to my conf.py extensions list. that fixes the broken uploads
      - name: Building documentation
        run: |
          pip install cython numpy pandas scikit-image scipy pytorch
          pip install sphinx sphinx_book_theme
          cd docs
          make html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/build/html # The folder the action should deploy.
